### ISSUE TITLE
Formatting of download bar is bugged for really small instances

### ISSUE THREAD

**Issue by duylethanh** [hu-macsy/simexpal#115]
``` yaml
instances:
  - method: url
    url: 'https://raw.githubusercontent.com/hu-macsy/simexpal/master/simexpal/schemes/@INSTANCE_FILENAME@'
    items:
      - 'experiments.json'
```

leads to

![grafik](https://user-images.githubusercontent.com/50080918/124316143-68bff800-db75-11eb-8439-100bc5afa2bf.png)
