### ISSUE TITLE
Document: Fileless Instance 

### ISSUE THREAD

**Issue by c-bebop** [hu-macsy/simexpal#130]
When I try setting up a file less instance as described under:
https://github.com/hu-macsy/simexpal/blob/master/docs/instances.rst#fileless-instances
I can't actually set a file less instance up as described.
In my case I have a file less instance defined as follows:
```yaml
  - repo: local
    set: [random]
    items:
      - name: random_graph
        files: []
        extra_args: ['--rand_g', '-d', 'instances/']
```
I am using the `random` instance set under `instsets` under the `matrix` map. 
When trying to launch my experiments simex throws the following error:
```bash
RuntimeError: The instance 'random_graph' is fileless
```

**Comment by duylethanh** [comment]
Can you post your ``experiments`` key? (at least the experiments that are supposed to use your fileless instance)

**Comment by c-bebop** [comment]
In this case it was the following:
```
  - name: static_init_memory
    use_builds: [benchmark]
    args: ['benchmark', '-a', 'none', '@EXTRA_ARGS@', 'file', '-p', '@INSTANCE@']
    stdout: out
    timeout: 1800
    num_threads: 36
```
But I figured, that the whole experiment setup was not what I desired so I am trying it another way now (with actual file instances). But I was still confused when looking at the documentation and my experiment setup: why it wouldn't work together.

**Comment by c-bebop** [comment]
Thanks for the reply, I've got it working as follows:

```yaml
  - name: random_graph_generation
    use_builds: [randgraph]
    args: ['randgraph', '-e', 'random_graph_generation', '@EXTRA_ARGS@']
    stdout: out
    timeout: 1800
    num_threads: 36

...

instances:
  - repo: local
    set: [file_less]
    items:
      - name: no_file
        files: []
```

As you say, it's without the `@INSTANCE@` key. Makes sense, but not documented yet.
