### ISSUE TITLE
undefined axis in run matrix does not cause an error

### ISSUE THREAD

**Issue by bernlu** [hu-macsy/simexpal#135]
Simex does not warn the user about undefined axes in the run matrix. Instead, the runs are just not added to the experiment list at all.

#### correct experiments.yml
```
instances:
  - repo: local
    items:
      - foo-inst

experiments:
  - name: foo
    args: ['@INSTANCE@', '@EXTRA_ARGS@']
    stdout: out

variants:
  - axis: 'ax1'
    items:
      - name: 'v1'
        extra_args: ['-v1']
      - name: 'v2'
        extra_args: ['-v2']

matrix:
  include:
    - experiments: [foo]
      axes: [ax1]
```
```
$ simex e list
Experiment                                    Instance                            Status
----------                                    --------                            ------
foo ~ v1                                      foo-inst                            [0] not submitted
foo ~ v2                                      foo-inst                            [0] not submitted
2 experiments in total
```

#### broken experiments.yml
(added undefined axis `bar` to the run matrix)
```
instances:
  - repo: local
    items:
      - foo-inst

experiments:
  - name: foo
    args: ['@INSTANCE@', '@EXTRA_ARGS@']
    stdout: out

variants:
  - axis: 'ax1'
    items:
      - name: 'v1'
        extra_args: ['-v1']
      - name: 'v2'
        extra_args: ['-v2']

matrix:
  include:
    - experiments: [foo]
      axes: [ax1, bar]
```
```
$ simex e list
Experiment                                    Instance                            Status
----------                                    --------                            ------
0 experiments in total
```
