### ISSUE TITLE
Runtime arguments

### ISSUE THREAD

**Issue by nizomovs** [hu-macsy/simexpal#176]
The `@EXTRA_ARGS@` @-variable used in the experiments `args` field only allows passing arguments to the experiment. However, runtime arguments can not be passed as an experimental parameter to the runtime.

For example: If you have an MPI application, you would have to hard code i.e. the number of nodes to be used.
```yml
experiments:
  - name: test
    args: ['srun', ..., '@EXTRA_ARGS@']
    num_nodes: 8
    stdout: out
```
Or using the built-in `num_nodes` fields:
```yml
experiments:
  - name: test
    args: ['srun', ..., '@EXTRA_ARGS@']
    num_nodes: 8
    stdout: out
```
If you wanted to run the same experiment but with a different number of nodes, you'd have to add a duplicate of that experiment and change the number of nodes.

It would be more convenient to add a `@RUNTIME_ARGS@` variable. The runtime arguments could be specified similarly to experiment arguments with variants and a matrix.
